### ISSUE TITLE
Parentheses must be used when instantiating a new class

### ISSUE THREAD

**Issue by MikeiLL** [CodeAtCode/CodeatCS#7]
A little confounded by this one:

```
$this->token_management = new TokenManagement;
```
Produces
```
82 | ERROR | [x] Parentheses must be used when instantiating a new class
```

```
$this->token_management = new TokenManagement();
```
Produces
```
 82 | ERROR | [x] Useless parentheses in "new".
```

**Comment by MikeiLL** [comment]
These are the only lines I'm seeing in the ruleset that reference parens:

`<exclude name="WordPress.Classes.ClassInstantiation.MissingParenthesis"/>`

https://github.com/CodeAtCode/CodeatCS/blob/efaac9250d6a02c8fe40dd26368b923a87cf252b/CodeatCodingStandard/ruleset.xml#L120

`<exclude name="SlevomatCodingStandard.ControlStructures.NewWithParentheses.MissingParentheses"/>`

https://github.com/CodeAtCode/CodeatCS/blob/efaac9250d6a02c8fe40dd26368b923a87cf252b/CodeatCodingStandard/ruleset.xml#L180

`<exclude name="PSR12.Classes.ClassInstantiation.MissingParentheses" />`

https://github.com/CodeAtCode/CodeatCS/blob/efaac9250d6a02c8fe40dd26368b923a87cf252b/CodeatCodingStandard/ruleset.xml#L231

**Comment by Mte90** [comment]
Did you updated the CodeatCS I fixed that issue yesterday as it was generated by the last rule missing that you mentioned.

Exclude just say don't use that rule, if you use phpcs wit the parameter `-s` shows what is the rule generating the error.

**Comment by MikeiLL** [comment]
Perfect. Thanks.
